/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    leads: Lead;
    products: Product;
    orders: Order;
    categories: Category;
    discounts: Discount;
    customers: Customer;
    testimonials: Testimonial;
    'newsletter-subscribers': NewsletterSubscriber;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    discounts: DiscountsSelect<false> | DiscountsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('th' | 'en') | ('th' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'th' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * สร้างและแก้ไขหน้าเว็บ พร้อมเพิ่ม Section เองได้จาก layout ด้านล่าง
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * เช่น "about", "csr" — หน้าแรกให้ใช้ "home"
   */
  slug: string;
  meta?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  layout?:
    | (
        | {
            image?: (number | null) | Media;
            heading: string;
            text?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageLeftTextRight';
          }
        | {
            image?: (number | null) | Media;
            heading: string;
            text?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageTopTextBottom';
          }
        | {
            heading: string;
            text?: string | null;
            images?:
              | {
                  image?: (number | null) | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageGallery';
          }
        | {
            layout?: ('single' | 'collage') | null;
            image?: (number | null) | Media;
            collageImages?:
              | {
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            heading: string;
            text?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            overlayColor?: ('dark' | 'gold') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBanner';
          }
        | {
            heading: string;
            text?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textOnly';
          }
        | {
            eyebrow?: string | null;
            tag?: string | null;
            heading: string;
            highlightText?: string | null;
            subheading?: string | null;
            subheadingHighlight?: string | null;
            quote?: string | null;
            layout?: ('centered' | 'split') | null;
            visualStyle?: ('photo' | 'brandMark') | null;
            image?: (number | null) | Media;
            imageStyle?: ('rounded' | 'circle') | null;
            primaryCtaLabel?: string | null;
            primaryCtaUrl?: string | null;
            secondaryCtaLabel?: string | null;
            secondaryCtaUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            logos?:
              | {
                  logo: number | Media;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoStrip';
          }
        | {
            heading: string;
            subheading?: string | null;
            columns?: ('2' | '3' | '4') | null;
            items: {
              icon?: (number | null) | Media;
              title: string;
              description?: string | null;
              points?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[];
            footnote?: string | null;
            sideImages?:
              | {
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'iconFeatureGrid';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            text?: string | null;
            points?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            images?:
              | {
                  image: number | Media;
                  id?: string | null;
                }[]
              | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureShowcase';
          }
        | {
            heading: string;
            subheading?: string | null;
            variant?: ('cards' | 'compact') | null;
            steps: {
              number?: string | null;
              title: string;
              description?: string | null;
              id?: string | null;
            }[];
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'processSteps';
          }
        | {
            image?: (number | null) | Media;
            exampleLabel?: string | null;
            exampleText?: string | null;
            timeline?:
              | {
                  label: string;
                  text: string;
                  color?: ('green' | 'orange' | 'red') | null;
                  id?: string | null;
                }[]
              | null;
            funnelColumns?:
              | {
                  theme?: ('blue' | 'purple' | 'pink') | null;
                  rows?:
                    | {
                        platforms?:
                          | {
                              label: string;
                              id?: string | null;
                            }[]
                          | null;
                        label: string;
                        mockCount?: number | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'exampleFunnelDiagram';
          }
        | {
            heading: string;
            items: {
              title: string;
              points?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[];
            phoneCount?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'workScopeGrid';
          }
        | {
            number?: string | null;
            heading: string;
            exampleLabel?: string | null;
            exampleText?: string | null;
            situation?: {
              heading?: string | null;
              points?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
            };
            whatWeDid?: {
              heading?: string | null;
              points?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
            };
            whatWeFound?: {
              heading?: string | null;
              points?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
            };
            result?: {
              heading?: string | null;
              points?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
            };
            comparisonGroups?:
              | {
                  label: string;
                  items?:
                    | {
                        text: string;
                        tag?: ('gold' | 'blue' | 'green' | 'red') | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'layerCaseStudy';
          }
        | {
            number?: string | null;
            heading: string;
            subheadingText?: string | null;
            subheadingHighlight?: string | null;
            items: {
              platforms?:
                | {
                    label: string;
                    icon?: (number | null) | Media;
                    id?: string | null;
                  }[]
                | null;
              title: string;
              description?: string | null;
              points?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'capabilityGrid';
          }
        | {
            number?: string | null;
            heading: string;
            flowSteps?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            insightHeading?: string | null;
            insightItems?:
              | {
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            actionHeading?: string | null;
            actionPoints?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            workingHeading?: string | null;
            workingPoints?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            summaryHeading?: string | null;
            summaryText?: string | null;
            nextActionHeading?: string | null;
            nextActionItems?:
              | {
                  tag: string;
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'insightActionPanel';
          }
        | {
            heading: string;
            subheading?: string | null;
            centerIcon?: (number | null) | Media;
            centerLabel: string;
            centerDescription?: string | null;
            painPointsIcon?: (number | null) | Media;
            painPointsHeading?: string | null;
            painPoints?:
              | {
                  icons?:
                    | {
                        icon: number | Media;
                        label?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            behaviorIcon?: (number | null) | Media;
            behaviorLabel?: string | null;
            behaviorDescription?: string | null;
            solutionsIcon?: (number | null) | Media;
            solutionsHeading?: string | null;
            solutionsItems?:
              | {
                  icon?: (number | null) | Media;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            impactIcon?: (number | null) | Media;
            impactHeading?: string | null;
            impactItems?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'businessCareLoop';
          }
        | {
            heading: string;
            freeSlotsLabel?: string | null;
            totalSlots?: number | null;
            bookedSlots?: number | null;
            rightTitle?: string | null;
            rightDescription?: string | null;
            features?:
              | {
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            originalPrice?: string | null;
            badgeText?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bookingPromo';
          }
        | {
            heading: string;
            subheading?: string | null;
            businessListHeading?: string | null;
            businessTypes?:
              | {
                  title: string;
                  points?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            serviceLabel?: string | null;
            serviceOptions?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'leadFormSection';
          }
        | {
            heading?: string | null;
            items: {
              year: string;
              title: string;
              description?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            heading?: string | null;
            items: {
              title: string;
              description?: string | null;
              points?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              footnote?: string | null;
              images?:
                | {
                    image: number | Media;
                    id?: string | null;
                  }[]
                | null;
              linkLabel?: string | null;
              linkUrl?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'caseStudyList';
          }
        | {
            heading?: string | null;
            items: {
              question: string;
              answer: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading: string;
            text?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            theme?: ('gold' | 'dark') | null;
            size?: ('full' | 'compact') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBanner';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            packages: {
              name: string;
              subtitle?: string | null;
              priceNote?: string | null;
              audienceLine?: string | null;
              platforms?:
                | {
                    label: string;
                    icon?: (number | null) | Media;
                    id?: string | null;
                  }[]
                | null;
              features?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              groups?:
                | {
                    label: string;
                    points?:
                      | {
                          text: string;
                          id?: string | null;
                        }[]
                      | null;
                    id?: string | null;
                  }[]
                | null;
              ctaLabel?: string | null;
              ctaUrl?: string | null;
              highlighted?: boolean | null;
              id?: string | null;
            }[];
            additionalNote?: {
              heading?: string | null;
              highlight?: string | null;
              badge?: string | null;
              text?: string | null;
              subtext?: string | null;
              points?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              ctaLabel?: string | null;
              ctaUrl?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricingPackages';
          }
        | {
            heading: string;
            subheading?: string | null;
            leftLabel?: string | null;
            leftImage: number | Media;
            rightLabel?: string | null;
            rightImage: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dualDiagram';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'diagramImage';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            mode?: ('featured' | 'all' | 'selected') | null;
            limit?: number | null;
            products?: (number | Product)[] | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productGrid';
          }
        | {
            heading?: string | null;
            images: {
              image?: (number | null) | Media;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'adsPortfolioGrid';
          }
        | {
            heading: string;
            /**
             * บริษัท/ที่อยู่/เบอร์โทร/LINE/โซเชียล ดึงมาจาก "ตั้งค่าเว็บไซต์ > ข้อมูลติดต่อ / โซเชียลมีเดีย" โดยอัตโนมัติ ไม่ต้องกรอกซ้ำที่นี่
             */
            text?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactInfo';
          }
        | {
            promoHeading: string;
            promoHighlight?: string | null;
            promoText?: string | null;
            checklistHeading: string;
            checklistHighlight?: string | null;
            items: {
              text: string;
              id?: string | null;
            }[];
            thresholdText?: string | null;
            thresholdCta?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'symptomChecklist';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * รายการสินค้าที่ขายในร้าน
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * เช่น "wooden-chair"
   */
  slug: string;
  sku?: string | null;
  price: number;
  compareAtPrice?: number | null;
  category?: (number | null) | Category;
  color?:
    | (
        | 'purple'
        | 'red'
        | 'orange'
        | 'white'
        | 'gray'
        | 'gold'
        | 'black'
        | 'green'
        | 'pink'
        | 'slate'
        | 'mint'
        | 'cream'
        | 'yellow'
        | 'blue'
        | 'brown'
      )
    | null;
  tags?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  width?: number | null;
  height?: number | null;
  depth?: number | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  shortDescription?: string | null;
  description?: string | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  inStock?: boolean | null;
  featured?: boolean | null;
  bestseller?: boolean | null;
  /**
   * กรอกเองจากรีวิวจริง ถ้ายังไม่มีปล่อยว่างไว้ได้
   */
  rating?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * หมวดหมู่สินค้าในร้าน
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Lead ที่กรอกจากหน้าเว็บ พร้อมวันที่ที่เลือกจองใน Calendar
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  business?: string | null;
  interestedService?: string | null;
  bookingDate?: string | null;
  bookingTime?: string | null;
  consentPDPA: boolean;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * คำสั่งซื้อที่ลูกค้าส่งมาจากตะกร้าสินค้าหน้าเว็บ
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  customerName: string;
  phone: string;
  email?: string | null;
  address?: string | null;
  note?: string | null;
  items: {
    product?: (number | null) | Product;
    productName: string;
    unitPrice: number;
    quantity: number;
    id?: string | null;
  }[];
  paymentMethod?: ('bank_transfer' | 'cod') | null;
  discountCode?: string | null;
  discountAmount?: number | null;
  totalAmount: number;
  status?: ('new' | 'contacted' | 'confirmed' | 'cancelled') | null;
  consentPDPA: boolean;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * โค้ดส่วนลดที่ลูกค้าใช้ตอนสั่งซื้อในตะกร้า
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discounts".
 */
export interface Discount {
  id: number;
  /**
   * ลูกค้าจะพิมพ์โค้ดนี้ในตะกร้า เช่น "SALE10"
   */
  code: string;
  type: 'percentage' | 'fixed';
  value: number;
  active?: boolean | null;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * ข้อมูลลูกค้า รวบรวมอัตโนมัติจากออเดอร์ที่เข้ามา
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  address?: string | null;
  totalOrders?: number | null;
  totalSpent?: number | null;
  lastOrderAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * รีวิวจากลูกค้าจริงเท่านั้น กรอกโดยแอดมินหลังได้รับความยินยอมจากลูกค้า — ห้ามใส่รีวิวสมมติ จะแสดงในหน้าร้านค้าเมื่อมีอย่างน้อย 1 รายการ
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  quote: string;
  rating?: number | null;
  avatar?: (number | null) | Media;
  verified?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * อีเมลที่สมัครรับข่าวสาร/โปรโมชันจากหน้าร้านค้า
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'discounts';
        value: number | Discount;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  meta?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  layout?:
    | T
    | {
        imageLeftTextRight?:
          | T
          | {
              image?: T;
              heading?: T;
              text?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
        imageTopTextBottom?:
          | T
          | {
              image?: T;
              heading?: T;
              text?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
        imageGallery?:
          | T
          | {
              heading?: T;
              text?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        imageBanner?:
          | T
          | {
              layout?: T;
              image?: T;
              collageImages?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              heading?: T;
              text?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              overlayColor?: T;
              id?: T;
              blockName?: T;
            };
        textOnly?:
          | T
          | {
              heading?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              eyebrow?: T;
              tag?: T;
              heading?: T;
              highlightText?: T;
              subheading?: T;
              subheadingHighlight?: T;
              quote?: T;
              layout?: T;
              visualStyle?: T;
              image?: T;
              imageStyle?: T;
              primaryCtaLabel?: T;
              primaryCtaUrl?: T;
              secondaryCtaLabel?: T;
              secondaryCtaUrl?: T;
              id?: T;
              blockName?: T;
            };
        logoStrip?:
          | T
          | {
              heading?: T;
              logos?:
                | T
                | {
                    logo?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        iconFeatureGrid?:
          | T
          | {
              heading?: T;
              subheading?: T;
              columns?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    points?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              footnote?: T;
              sideImages?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              ctaLabel?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
        featureShowcase?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              text?: T;
              points?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              ctaLabel?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
        processSteps?:
          | T
          | {
              heading?: T;
              subheading?: T;
              variant?: T;
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              ctaLabel?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
        exampleFunnelDiagram?:
          | T
          | {
              image?: T;
              exampleLabel?: T;
              exampleText?: T;
              timeline?:
                | T
                | {
                    label?: T;
                    text?: T;
                    color?: T;
                    id?: T;
                  };
              funnelColumns?:
                | T
                | {
                    theme?: T;
                    rows?:
                      | T
                      | {
                          platforms?:
                            | T
                            | {
                                label?: T;
                                id?: T;
                              };
                          label?: T;
                          mockCount?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        workScopeGrid?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    points?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              phoneCount?: T;
              id?: T;
              blockName?: T;
            };
        layerCaseStudy?:
          | T
          | {
              number?: T;
              heading?: T;
              exampleLabel?: T;
              exampleText?: T;
              situation?:
                | T
                | {
                    heading?: T;
                    points?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                  };
              whatWeDid?:
                | T
                | {
                    heading?: T;
                    points?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                  };
              whatWeFound?:
                | T
                | {
                    heading?: T;
                    points?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                  };
              result?:
                | T
                | {
                    heading?: T;
                    points?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                  };
              comparisonGroups?:
                | T
                | {
                    label?: T;
                    items?:
                      | T
                      | {
                          text?: T;
                          tag?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        capabilityGrid?:
          | T
          | {
              number?: T;
              heading?: T;
              subheadingText?: T;
              subheadingHighlight?: T;
              items?:
                | T
                | {
                    platforms?:
                      | T
                      | {
                          label?: T;
                          icon?: T;
                          id?: T;
                        };
                    title?: T;
                    description?: T;
                    points?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        insightActionPanel?:
          | T
          | {
              number?: T;
              heading?: T;
              flowSteps?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              insightHeading?: T;
              insightItems?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              actionHeading?: T;
              actionPoints?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              workingHeading?: T;
              workingPoints?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              summaryHeading?: T;
              summaryText?: T;
              nextActionHeading?: T;
              nextActionItems?:
                | T
                | {
                    tag?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        businessCareLoop?:
          | T
          | {
              heading?: T;
              subheading?: T;
              centerIcon?: T;
              centerLabel?: T;
              centerDescription?: T;
              painPointsIcon?: T;
              painPointsHeading?: T;
              painPoints?:
                | T
                | {
                    icons?:
                      | T
                      | {
                          icon?: T;
                          label?: T;
                          id?: T;
                        };
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              behaviorIcon?: T;
              behaviorLabel?: T;
              behaviorDescription?: T;
              solutionsIcon?: T;
              solutionsHeading?: T;
              solutionsItems?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              impactIcon?: T;
              impactHeading?: T;
              impactItems?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        bookingPromo?:
          | T
          | {
              heading?: T;
              freeSlotsLabel?: T;
              totalSlots?: T;
              bookedSlots?: T;
              rightTitle?: T;
              rightDescription?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              originalPrice?: T;
              badgeText?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
        leadFormSection?:
          | T
          | {
              heading?: T;
              subheading?: T;
              businessListHeading?: T;
              businessTypes?:
                | T
                | {
                    title?: T;
                    points?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              serviceLabel?: T;
              serviceOptions?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    year?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        caseStudyList?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    points?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    footnote?: T;
                    images?:
                      | T
                      | {
                          image?: T;
                          id?: T;
                        };
                    linkLabel?: T;
                    linkUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBanner?:
          | T
          | {
              heading?: T;
              text?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              theme?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
        pricingPackages?:
          | T
          | {
              heading?: T;
              subheading?: T;
              packages?:
                | T
                | {
                    name?: T;
                    subtitle?: T;
                    priceNote?: T;
                    audienceLine?: T;
                    platforms?:
                      | T
                      | {
                          label?: T;
                          icon?: T;
                          id?: T;
                        };
                    features?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    groups?:
                      | T
                      | {
                          label?: T;
                          points?:
                            | T
                            | {
                                text?: T;
                                id?: T;
                              };
                          id?: T;
                        };
                    ctaLabel?: T;
                    ctaUrl?: T;
                    highlighted?: T;
                    id?: T;
                  };
              additionalNote?:
                | T
                | {
                    heading?: T;
                    highlight?: T;
                    badge?: T;
                    text?: T;
                    subtext?: T;
                    points?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    ctaLabel?: T;
                    ctaUrl?: T;
                  };
              id?: T;
              blockName?: T;
            };
        dualDiagram?:
          | T
          | {
              heading?: T;
              subheading?: T;
              leftLabel?: T;
              leftImage?: T;
              rightLabel?: T;
              rightImage?: T;
              id?: T;
              blockName?: T;
            };
        diagramImage?:
          | T
          | {
              heading?: T;
              subheading?: T;
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        productGrid?:
          | T
          | {
              heading?: T;
              subheading?: T;
              mode?: T;
              limit?: T;
              products?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
        adsPortfolioGrid?:
          | T
          | {
              heading?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactInfo?:
          | T
          | {
              heading?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        symptomChecklist?:
          | T
          | {
              promoHeading?: T;
              promoHighlight?: T;
              promoText?: T;
              checklistHeading?: T;
              checklistHighlight?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              thresholdText?: T;
              thresholdCta?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  business?: T;
  interestedService?: T;
  bookingDate?: T;
  bookingTime?: T;
  consentPDPA?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sku?: T;
  price?: T;
  compareAtPrice?: T;
  category?: T;
  color?: T;
  tags?:
    | T
    | {
        text?: T;
        id?: T;
      };
  width?: T;
  height?: T;
  depth?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  shortDescription?: T;
  description?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  inStock?: T;
  featured?: T;
  bestseller?: T;
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  customerName?: T;
  phone?: T;
  email?: T;
  address?: T;
  note?: T;
  items?:
    | T
    | {
        product?: T;
        productName?: T;
        unitPrice?: T;
        quantity?: T;
        id?: T;
      };
  paymentMethod?: T;
  discountCode?: T;
  discountAmount?: T;
  totalAmount?: T;
  status?: T;
  consentPDPA?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discounts_select".
 */
export interface DiscountsSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  value?: T;
  active?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  address?: T;
  totalOrders?: T;
  totalSpent?: T;
  lastOrderAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  quote?: T;
  rating?: T;
  avatar?: T;
  verified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  logo?: (number | null) | Media;
  navLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerServices?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerPortfolio?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  tracking?: {
    ga4Id?: string | null;
    gtmId?: string | null;
    gscVerification?: string | null;
    fbPixelId?: string | null;
    tiktokPixelId?: string | null;
    linePixelId?: string | null;
  };
  /**
   * กรอกข้อมูลบัญชีจริงของร้าน เพื่อแสดงในหน้าตะกร้าให้ลูกค้าโอนเงิน — ถ้าปล่อยว่าง ระบบจะแจ้งลูกค้าว่าทีมงานจะติดต่อแจ้งภายหลัง
   */
  payment?: {
    bankName?: string | null;
    accountName?: string | null;
    accountNumber?: string | null;
    promptPayId?: string | null;
    qrImage?: (number | null) | Media;
  };
  contact?: {
    companyName?: string | null;
    address?: string | null;
    phone?: string | null;
    phoneIcon?: (number | null) | Media;
    lineUrl?: string | null;
    lineLabel?: string | null;
    lineIcon?: (number | null) | Media;
    email?: string | null;
  };
  socialLinks?: {
    facebookUrl?: string | null;
    facebookLabel?: string | null;
    facebookIcon?: (number | null) | Media;
    instagramUrl?: string | null;
    instagramLabel?: string | null;
    instagramIcon?: (number | null) | Media;
    tiktokUrl?: string | null;
    tiktokLabel?: string | null;
    tiktokIcon?: (number | null) | Media;
    youtubeUrl?: string | null;
    youtubeLabel?: string | null;
    youtubeIcon?: (number | null) | Media;
  };
  headerCta?: {
    label?: string | null;
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  navLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerServices?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerPortfolio?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  tracking?:
    | T
    | {
        ga4Id?: T;
        gtmId?: T;
        gscVerification?: T;
        fbPixelId?: T;
        tiktokPixelId?: T;
        linePixelId?: T;
      };
  payment?:
    | T
    | {
        bankName?: T;
        accountName?: T;
        accountNumber?: T;
        promptPayId?: T;
        qrImage?: T;
      };
  contact?:
    | T
    | {
        companyName?: T;
        address?: T;
        phone?: T;
        phoneIcon?: T;
        lineUrl?: T;
        lineLabel?: T;
        lineIcon?: T;
        email?: T;
      };
  socialLinks?:
    | T
    | {
        facebookUrl?: T;
        facebookLabel?: T;
        facebookIcon?: T;
        instagramUrl?: T;
        instagramLabel?: T;
        instagramIcon?: T;
        tiktokUrl?: T;
        tiktokLabel?: T;
        tiktokIcon?: T;
        youtubeUrl?: T;
        youtubeLabel?: T;
        youtubeIcon?: T;
      };
  headerCta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}